### ISSUE TITLE
Move to saltstack org

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/rng-tools-formula#1]
@myii This formula is ~near~ ready to be moved to [saltstack-formulas](https://github.com/saltstack-formulas).

https://travis-ci.com/github/n-rodriguez/rng-tools-formula/builds/183640394

Tests fail on `default-opensuse-leap-152-*` because it's a docker container.

The service doesn't start :

```sh
25b27cb50e78:/home/kitchen # systemctl status rng-tools
● rng-tools.service - Start the rngd daemon
   Loaded: loaded (/usr/lib/systemd/system/rng-tools.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Wed 2020-09-09 22:10:12 UTC; 4s ago
           └─ ConditionVirtualization=!container was not met
```

If you comment the line in systemd service file (`ConditionVirtualization`) it works and test pass :

```systemd
[Unit]
Description=Start the rngd daemon
ConditionVirtualization=!container
Conflicts=haveged.service

[Service]
CapabilityBoundingSet=CAP_SYS_ADMIN
ExecStart=/usr/sbin/rngd --foreground --fill-watermark=3700

[Install]
WantedBy=multi-user.target
Alias=rngd.service
```

**Comment by n-rodriguez** [comment]
@myii feel free to make your traditional PR that adds missing parts :)

**Comment by myii** [comment]
> @myii This formula is ~near~ ready to be moved to [saltstack-formulas](https://github.com/saltstack-formulas).

@n-rodriguez Great!  The method that works best is to _transfer_ rather than _fork_ the repo into the org.  You already have the permissions to do that, so feel free to go ahead.  Once it's in place, I'll provide the PR using the `ssf-formula`.

**Comment by n-rodriguez** [comment]
great!

**Comment by n-rodriguez** [comment]
@myii done!

**Comment by myii** [comment]
> @myii done!

@n-rodriguez Thanks, I'll check this out in the next day or so.  We can leave this issue open until I provide that PR.

**Comment by myii** [comment]
Added to Taiga: https://tree.taiga.io/project/myii-saltstack-formulas/task/397.

**Comment by myii** [comment]
Made a separate issue for the `ConditionVirtualization` situation here: #3.

**Comment by myii** [comment]
Just a note, I got stuck on this process for ages because of the CI debug spam issue:

* https://travis-ci.org/github/myii/rng-tools-formula/jobs/726745952#L2403

After a lot of mucking around, eventually applied the workaround to the pre-salted images themselves:

* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/52
